---
title: "M.M. Quick Tutorial"
author: "Dietrich Epp Schmidt"
date: "5/18/2020"
output: html_document
---


First, let's install Model.Microbiome:
```{r}
devtools::install_github("(“djeppschmidt/Model.Microbiome”")
```
Now load all the other packages we need (or download and load if you haven't already):
```{r}
# load required packages ####

library(Model.Microbiome)
library(reshape2)
library(ggplot2)
library(vegan)
library(dplyr)
library(plyr)
library(phyloseq)
library(viridis)
library(ranacapa)
library(edgeR)
library(limma)
library(GLDEX)
library(stats)
```

```{r}
# new functions for more flexible use ####
#raw<-function(ps){ps}

RA<-function(ps){
  s<-transform_sample_counts(ps, function(x) x / sum(x))
  s
  }
eRare<-function(ps, level=NULL){
  if(is.null(level)){
  out<-make.rarefy2(ps, min(sample_sums(ps)))}
  else{
    out<-make.rarefy2(ps, level)}
  
  out
  }
pRare<-function(ps, level=NULL){
  if(is.null(level)){
  out<-make.rarefy2(ps, min(sample_sums(ps))*sample_sums(ps)/mean(sample_sums(ps)))} else{out<-make.rarefy2(ps, level)}
  
  out
}

QSeq<-function(ps, D){
  if(is.null(D)){print("QSeq Error: enter scaling factor D=...")}
  out<-make.scaled2(ps, val=sample_sums(ps)/mean(sample_sums(ps)), scale=D)
  out
  }
deseqVST<-function(ps){
  out<-make.deseqVST(output$raw$comm, "Factor", l=1)
  out
}
limmaVST<-function(ps){
  out<-make.limmaVST(output$raw$comm, "Factor")
  out
}



  #' workhorse function for benchmark.MM version 2 with flexible inputs
  #' @param commonN number of common species
  #' @param groupN number of unique taxa to groups
  #' @param singleN number of unique taxa to samples
  #' @param D average sampling depth
  #' @param V variation in sampling depth
  #' @param method new normalization function to implement
  #' @keywords benchmark
  #' @export
  #' @examples
  #' run.analysis()
  run.analysis2<-function(commonN, groupN, singleN, D, V, method){
      AllSpp<-c(paste0("spp", c(1:700), sep="")) # make a quick list of all species functions
      AllSpp<-lapply(AllSpp, get) # connect function to name
      AllSpp<-unlist(AllSpp)  # format to be read by downstream functions
      names(AllSpp)<-c(paste0("spp", c(1:700)))

      # Define list of 5 species w/ global distribution
      global.spp<-names(sample(AllSpp, commonN, replace=F))

  # define list of species w/ regional distribution
      group.spp<-NULL
      group.spp$group1<-names(sample(AllSpp, groupN, replace=F))
      group.spp$group2<-names(sample(AllSpp, groupN, replace=F))
      group.spp$group3<-names(sample(AllSpp, groupN, replace=F))
      group.spp$group4<-names(sample(AllSpp, groupN, replace=F))
      group.spp$group5<-names(sample(AllSpp, groupN, replace=F))
      group.spp$group6<-names(sample(AllSpp, groupN, replace=F))

  # define list of species found at each site
      rando.spp<-NULL
      rando.spp$Site1<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group1), global.spp))
      rando.spp$Site2<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group1), global.spp))
      rando.spp$Site3<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group1), global.spp))
      rando.spp$Site4<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group1), global.spp))
      rando.spp$Site5<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group1), global.spp))
      rando.spp$Site6<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group2), global.spp))
      rando.spp$Site7<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group2), global.spp))
      rando.spp$Site8<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group2), global.spp))
      rando.spp$Site9<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group2), global.spp))
      rando.spp$Site10<-unique(c(names(sample(AllSpp,singleN, replace=F)), c(group.spp$group2), global.spp))
      rando.spp$Site11<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group3), global.spp))
      rando.spp$Site12<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group3), global.spp))
      rando.spp$Site13<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group3), global.spp))
      rando.spp$Site14<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group3), global.spp))
      rando.spp$Site15<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group3), global.spp))
      rando.spp$Site16<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group4), global.spp))
      rando.spp$Site17<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group4), global.spp))
      rando.spp$Site18<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group4), global.spp))
      rando.spp$Site19<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group4), global.spp))
      rando.spp$Site20<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group4), global.spp))
      rando.spp$Site21<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group5), global.spp))
      rando.spp$Site22<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group5), global.spp))
      rando.spp$Site23<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group5), global.spp))
      rando.spp$Site24<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group5), global.spp))
      rando.spp$Site25<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group5), global.spp))
      rando.spp$Site26<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group6), global.spp))
      rando.spp$Site27<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group6), global.spp))
      rando.spp$Site28<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group6), global.spp))
      rando.spp$Site29<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group6), global.spp))
      rando.spp$Site30<-unique(c(names(sample(AllSpp, singleN, replace=F)), c(group.spp$group6), global.spp))

  # make list of unique species arrays

      library(reshape2)
      f1c1<-c(5,5,5,5,5,5) # number of selections
      f1c2<-c(1,3,10,30,60,15) # mean value of selections
      f1c3<-c(0.5,1,4,10,20,5) # SD of selections
      F1.frame<-mapply(rnorm, f1c1,f1c2,f1c3) # pick Factor 1 value for each site
      F1<-reshape2::melt(F1.frame)

  #F2
      f2c1<-c(5,5,5,5,5,5) # number of selections
      f2c2<-c(34,30,10,55,35,60) # mean value of selections
      f2c3<-c(10,10,3,10,1,20) # SD of selections
      F2.frame<-mapply(rnorm, f2c1,f2c2,f2c3) # pick Factor 2 value for each site
      F2<-reshape2::melt(F2.frame)

  #F3
      f3c1<-c(5,5,5,5,5,5) # number of selections
      f3c2<-c(1,3,10,15,3,15) # mean value of selections
      f3c3<-c(0.5,1,3,3,1,5) # SD of selections
      F3.frame<-mapply(rnorm, f3c1,f3c2,f3c3) # pick Factor 3 value for each site
      F3<-reshape2::melt(F3.frame)

  #F4
      f4c1<-c(5,5,5,5,5,5) # number of selections
      f4c2<-c(5,5,5,5,5,5) # mean value of selections
      f4c3<-c(1,1,1,1,1,1) # SD of selections
      F4.frame<-mapply(rnorm, f4c1,f4c2,f4c3) # pick Factor 4 value for each site
      F4<-reshape2::melt(F4.frame)

  #F5
      f5c1<-c(5,5,5,5,5,5) # number of selections
      f5c2<-c(50,50,50,50,50,50) # mean value of selections
      f5c3<-c(20,20,20,20,20,20) # SD of selections
      F5.frame<-mapply(rnorm, f5c1,f5c2,f5c3) # pick Factor 5 value for each site
      F5<-reshape2::melt(F5.frame)
      Factors<-data.frame(F1$value,F2$value,F3$value,F4$value,F5$value) # combine factors into data table
      Sites<-c(paste0("Site", 1:30))
      rownames(Factors)<-Sites
      colnames(Factors)<-c("F1","F2","F3","F4","F5")

      output<-list("model"=NULL, "spplist"=NULL, "raw"=NULL, "RA"=NULL, "eRare"=NULL, "pRare"=NULL, "scaled"=NULL, "deseqVST"=NULL, "deseqVST_scaled"=NULL, "limma"=NULL)

      #output$model<-NULL
      output$spplist<-rando.spp

      output$model$comm<-make.refcomm(rando.spp, Factors) # output a phyloseq object... will make a list of phyloseq objects
      output$model$comm<-filter_taxa(output$model$comm, function(x) sum(x)>0, TRUE)
      output$model$EV<-transform_sample_counts(output$model$comm, function(x) x / sum(x) )
      output$metrics<-NULL
      output$metrics$stats<-NULL
      output$metrics$Richness<-NULL
      Rich<-estimate_richness(output$model$comm, measures="Observed")
      output$metrics$Richness<-Rich
      output$metrics$skewness<-median(apply(X = otu_table(output$model$comm), MARGIN=2,FUN = function(x){skewness(x)}))
      #output$metrics$skewness.raw<-median(apply(X = otu_table(output$raw$comm), MARGIN=2,FUN = function(x){skewness(x)}))
      sample<-set.seqDepth(D,V)

      output$raw$comm<-model.rarefy(output$model$comm, sample)

      print("spp selection complete")
      sample_data(output$model$comm)$Density<-sample_sums(output$model$comm)# add sample sums
      sample_data(output$model$comm)$DensityF<-sample_sums(output$model$comm)/mean(sample_sums(output$model$comm))
      sample_data(output$model$comm)$Factor<-as.factor(c(rep("one",5),rep("two",5),rep("three",5),rep("four",5),rep("five",5),rep("six",5)))
      sample_data(output$model$comm)$Factor2<-as.factor(c(rep(1,5),rep(2,5),rep(3,5),rep(4,5),rep(5,5),rep(6,5)))


      print("start subsampling")
      # remove taxa that have zero abundance in "raw" sequencing run
      tax.filt<-filter_taxa(output$raw$comm, function(x)sum(x)>0)
      output$metrics$tax.lost<-tax.filt
        output$raw$comm<-filter_taxa(output$raw$comm, function(x)sum(x)>0, TRUE)
        # remove taxa that are not kept from sequencing so that they don't penalize downstream methods
        output$model$comm<-prune_taxa(tax.filt, output$model$comm)
        output$model$EV<-prune_taxa(tax.filt, output$model$EV)


      # for each species: measure prevalence
          prevalence=apply(X = otu_table(output$model$comm), MARGIN=1,FUN = function(x){sum(x > 0)})
      # for each species: measure relative abundance (proportion of total counts?
          p.abund<-transform_sample_counts(output$model$comm, function(x) x/sum(x) )

          mean_abundance<-apply(X = otu_table(p.abund), MARGIN=1,FUN = function(x){mean(x)})

          sd_abundance<-apply(X = otu_table(p.abund), MARGIN=1,FUN = function(x){sd(x)})
      # create a tax table for whole dataset ...
          tab<-data.frame(prevalence, mean_abundance, sd_abundance)
          tab$names<-rownames(tab)
          output$model$SpeciesMeta<-tab

          output$model$R<-lm.test(output$model$comm)

      # make expected value
          s<-sample_sums(output$raw$comm)
          s2<-as.data.frame(as.matrix(otu_table(output$model$EV)))
          s2<-for (i in 1:ncol(s2)) {s2[,i]<-s2[,i]*s[i]}
          otu_table(output$model$EV)<-otu_table(output$model$EV, taxa_are_rows=TRUE)
          M.Eval<-apply(X = otu_table(output$model$EV), MARGIN=1,FUN = function(x){mean(x[x>0])})


      #output$model$SpeciesMeta$USI<-output$model$SpeciesMeta$
      # create a tax table for whole dataset ...
          tab<-data.frame(prevalence, mean_abundance, sd_abundance, M.Eval)
          tab$names<-rownames(tab)
          output$model$SpeciesMeta<-tab
          output$model$R<-lm.test(output$model$comm)
          sample_data(output$raw$comm)<-sample_data(output$model$comm)
  print("metadata complete")
      # remove taxa that have zero abundance in "raw" sequencing run
# prepare raw metadata for lm analysis and model for lm analysis
      output$raw$PERMANOVA<-make.PERMANOVA(output$raw$comm)
      output$raw$LII<-LII(output$model$comm, output$raw$comm)
      output$raw$lmtab<-lm.model(output$raw$comm) # error here!
      output$model$lmtab<-lm.model(output$model$comm)
      output$raw$Dtab<-output$model$lmtab-output$raw$lmtab
      output$RA$comm<-transform_sample_counts(output$raw$comm, function(x) x / sum(x) )

     # output$eRare$comm<-make.rarefy2(output$raw$comm, min(sample_sums(output$raw$comm)))
     # print("erare complete")
    #  output$pRare$comm<-make.rarefy2(output$raw$comm, min(sample_sums(output$raw$comm))*sample_sums(output$raw$comm)/mean(sample_sums(output$raw$comm)))
    #  print("prare complete")
    #  output$scaled$comm<-make.scaled2(output$raw$comm, val=sample_sums(output$model$comm)/mean(sample_sums(output$model$comm)), scale=D)
     # print("scaling complete")
      #output$deseqVST$comm<-make.deseqVST(output$raw$comm, "Factor", l=1)
      #print("deseq complete")
      #output$deseqVST_scaled$comm<-make.deseqVST(output$scaled$comm, "Factor", l=1)
    #  output$limma$comm<-make.limmaVST(output$raw$comm, "Factor")
     # print("limma complete")
      #method.names<-method
      #method<-lapply(method, get)
      #method<-unlist(method)
      #names(method)<method.names
      method2<-c("RA", "eRare", "pRare", "QSeq", "DeseqVst", "limmaVst", method)
      for (i in 1:length(method2)){
        a<-get(method2[i])
        #name(a)<-i
        b<-output$raw$comm
        c<-a(b)
        output[[method2[i]]]$comm<-c
        output[[method2[i]]]$PERMANOVA<-make.PERMANOVA(c)
        output[[method2[i]]]$LII<-LII(output$model$comm, output[[i]]$comm)

      }
print("normalizing complete")
  # do 1- : calculates the information lost
  #  for (i in 1:length(method2)){
      # make the species-wise LII value:
  #    output$model$SpeciesMeta[[method2[i]]]<-1-output[[paste(method2[i],"LII")]]$LII$R
      # make the lm output for each normalization: (this is rsquared, could be r value ...)
  #    output[[method2[i]]]$lmtab<-lm.model(output[[method2[i]]]$comm)
      # conditional statement to make sure that the taxon names match, then:
      # difference in rsquared values (or r values?) from reference:
 #     if(rownames(output$model$lmtab)==rownames(output[[method2[i]]]$lmtab)){
#      output[[method2[i]]]$Dtab<-output$model$lmtab-output[[method2[i]]]$lmtab}
  #    else{print("Error in Dtab: names do not match")}
  #  }
    output
  }


  lm.model<-function(ps){
  anova.otu<-as.data.frame(t(as.matrix(otu_table(ps))))
  anova.env<-data.frame(as.matrix(sample_data(ps)))
  anova.env$F1<-as.numeric(as.character(anova.env$F1))
  anova.env$F2<-as.numeric(as.character(anova.env$F2))
  anova.env$F3<-as.numeric(as.character(anova.env$F3))
  anova.env$F4<-as.numeric(as.character(anova.env$F4))
  anova.env$F5<-as.numeric(as.character(anova.env$F5))

  testlm<-ddply(anova.otu, 2, function(x) {
    #l1=summary(lm(x~anova.env$Factor+anova.env$F1+anova.env$F2+anova.env$F3+anova.env$F4+anova.env$F5))
    l1=summary(lm(x~anova.env$F1+anova.env$F2+anova.env$F3+anova.env$F4+anova.env$F5))
    return(l1$r.squared)
    })
  testlm[is.na(testlm)]<-0
  testlm<-testlm[order(names(testlm))]
  testlm
  }
  
  
  
  # test funcitons ####

  method<-c("RA", "eRare","pRare","deseqVST", "limmaVST") 
  
 test.analysis<-run.analysis2(commonN=30, groupN=20, singleN=5, D=500, V=250, method) 
```



```{r}

```

```{r}

```

